create table ai_models
(
    id                     int                                not null primary key auto_increment,
    natural_id             varchar(100)                       not null,
    provider_id            int                                not null,
    name                   varchar(100)                       not null,
    uri                    varchar(1000),
    api_key                varchar(500),
    enabled                boolean              default true  not null,
    `default`              boolean              default false not null,
    embedding              boolean                            not null,
    model_name             varchar(100),
    temperature            decimal,
    top_p                  decimal,
    top_k                  int,
    frequency_penalty      decimal,
    presence_penalty       decimal,
    thinking               boolean              default false not null,
    maximum_context_length int                                not null,
    maximum_output_tokens  int,
    stop_sequences         varchar(5000)                      not null,
    response_format        enum ('TEXT','JSON') default 'TEXT',
    created_at             datetime                           not null,
    modified_at            datetime,
    tags                   varchar(500),
    description            varchar(1000),
    constraint nk$ai_models$natural_id unique key (natural_id),
    constraint fk$ai_models$provider_id foreign key (provider_id) references ai_providers (id)
) ENGINE = InnoDB;